Elcodi\Component\Tax\Entity\TaxGroup:
    type: entity
    repositoryClass: Elcodi\Component\Tax\Repository\TaxGroupRepository
    table: tax_group
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            column: name
            type: string
            length: 15
            nullable: false
        description:
            column: description
            type: string
            length: 255
            nullable: false

    oneToMany:
        taxes:
            targetEntity: Elcodi\Component\Tax\Entity\Interfaces\TaxInterface
            mappedBy: taxGroup
